blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/logos-ide/logos/discussions
    about: ä½¿ç”¨è®¨è®ºåŒºè¿›è¡Œé—®ç­”å’Œä¸€èˆ¬æ€§è®¨è®º
  - name: ğŸ“– æ–‡æ¡£
    url: https://logos-ide.github.io/docs
    about: æŸ¥çœ‹å®˜æ–¹æ–‡æ¡£è·å–ä½¿ç”¨å¸®åŠ©